### ISSUE TITLE
Is the influxdb_stats_exporter Helmchart available in any repository?

### ISSUE THREAD

**Issue by giddel** [carlpett/influxdb_stats_exporter#11]
... because I cannot find it?

**Comment by carlpett** [comment]
Hi @giddel,
No, it is not published anywhere, and is probably best seen as a starting point for what you could publish to an internal repository.
If you'd like to publish the contributed chart somewhere, or a new one, feel free to do so! I'm personally not using the chart, and do not have time to maintain it.

**Comment by giddel** [comment]
Yes, I feared that. And so I already use it internal :-)
