### ISSUE TITLE
Helm Chart?

### ISSUE THREAD

**Issue by jarett-cyxtera** [carlpett/influxdb_stats_exporter#8]
Hi @carlpett,

When we deployed the influxdb_stats_exporter in our environments I didn't find an existing Helm chart for it so I created a simple one.  Would you be interested in the chart being part of the main repo?

You can view the changes in this branch: [helm-ssl-skip-verify](https://github.com/carlpett/influxdb_stats_exporter/compare/master...jarett-cyxtera:helm-ssl-skip-verify)

Thanks!

**Comment by carlpett** [comment]
Hey @jarett-cyxtera,
That looks nice, and I'll happily accept a PR with it! :)
